Use the read_excel function of the pandas package to read the data into a dataframe wh_all_df

In [1]:
import pandas as pd

In [3]:
#pd.read_excel?
wh_all_df = pd.read_excel('WHR21.xls')

In [4]:
wh_all_df

,Country name,year,Life Ladder,Log GDP per capita,Social support,Healthy life expectancy at birth,Freedom to make life choices,Generosity,Perceptions of corruption,Positive affect,...,GINI index (World Bank estimate),"GINI index (World Bank estimate), average 2000-2017, unbalanced panel","gini of household income reported in Gallup, by wp5-year","Most people can be trusted, Gallup","Most people can be trusted, WVS round 1981-1984","Most people can be trusted, WVS round 1989-1993","Most people can be trusted, WVS round 1994-1998","Most people can be trusted, WVS round 1999-2004","Most people can be trusted, WVS round 2005-2009","Most people can be trusted, WVS round 2010-2014"
0,Australia,2005,7.340688,10.570512,0.967892,71.400002,0.934973,NaN,0.390416,0.842648,...,NaN,0.343333,NaN,NaN,0.478149,NaN,0.394492,NaN,0.461379,0.518140
1,Belgium,2005,7.262290,10.591697,0.934875,69.900002,0.923843,NaN,0.597554,0.796279,...,0.293,0.284308,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Brazil,2005,6.636771,9.421541,0.882923,63.299999,0.882186,NaN,0.744994,0.818337,...,0.563,0.545812,NaN,NaN,NaN,0.066020,NaN,NaN,0.093811,0.070638
3,Canada,2005,7.418048,10.609852,0.961552,71.300003,0.957306,0.249932,0.502681,0.838544,...,NaN,0.336800,NaN,NaN,NaN,NaN,NaN,0.385469,0.418500,NaN
4,Czech Republic,2005,6.439257,10.157401,0.918759,67.000000,0.865235,NaN,0.900733,0.722875,...,0.269,0.264167,NaN,NaN,NaN,0.302275,0.285192,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1992,Venezuela,2020,4.892200,9.073104,0.860927,66.699860,0.615380,-0.168757,0.826656,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1993,Vietnam,2020,5.410800,8.973157,0.849987,68.034134,0.939593,-0.097614,0.796421,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1994,Yemen,2020,3.657900,7.578437,0.831537,57.121571,0.602157,-0.146712,0.800288,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1995,Zambia,2020,4.073400,8.145451,0.707518,55.809212,0.781900,0.060521,0.823431,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1996,Zimbabwe,2020,3.144800,7.942595,0.750470,56.200840,0.676700,-0.047346,0.820999,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
wh_all_df.columns

Index(['Country name', 'year', 'Life Ladder', 'Log GDP per capita',
       'Social support', 'Healthy life expectancy at birth',
       'Freedom to make life choices', 'Generosity',
       'Perceptions of corruption', 'Positive affect', 'Negative affect',
       'Confidence in national government', 'Democratic Quality',
       'Delivery Quality', 'Standard deviation of ladder by country-year',
       'Standard deviation/Mean of ladder by country-year',
       'GINI index (World Bank estimate)',
       'GINI index (World Bank estimate), average 2000-2017, unbalanced panel',
       'gini of household income reported in Gallup, by wp5-year',
       'Most people can be trusted, Gallup',
       'Most people can be trusted, WVS round 1981-1984',
       'Most people can be trusted, WVS round 1989-1993',
       'Most people can be trusted, WVS round 1994-1998',
       'Most people can be trusted, WVS round 1999-2004',
       'Most people can be trusted, WVS round 2005-2009',
       'Most people can be trusted, WVS round 2010-2014'],
      dtype='object')

In [11]:
cols_of_interest = wh_all_df.columns[1:9]

In [12]:
wh_withna_df = wh_all_df[cols_of_interest]

In [13]:
wh_withna_df

,year,Life Ladder,Log GDP per capita,Social support,Healthy life expectancy at birth,Freedom to make life choices,Generosity,Perceptions of corruption
0,2005,7.340688,10.570512,0.967892,71.400002,0.934973,NaN,0.390416
1,2005,7.262290,10.591697,0.934875,69.900002,0.923843,NaN,0.597554
2,2005,6.636771,9.421541,0.882923,63.299999,0.882186,NaN,0.744994
3,2005,7.418048,10.609852,0.961552,71.300003,0.957306,0.249932,0.502681
4,2005,6.439257,10.157401,0.918759,67.000000,0.865235,NaN,0.900733
...,...,...,...,...,...,...,...,...
1992,2020,4.892200,9.073104,0.860927,66.699860,0.615380,-0.168757,0.826656
1993,2020,5.410800,8.973157,0.849987,68.034134,0.939593,-0.097614,0.796421
1994,2020,3.657900,7.578437,0.831537,57.121571,0.602157,-0.146712,0.800288
1995,2020,4.073400,8.145451,0.707518,55.809212,0.781900,0.060521,0.823431
1996,2020,3.144800,7.942595,0.750470,56.200840,0.676700,-0.047346,0.820999

In [ ]:
xxx = wh_all_df[]

In [15]:
import seaborn as sns